### ISSUE TITLE
Not sure this repo is needed (please check out of the box support for consolidation)

### ISSUE THREAD

**Issue by bistaray** [OCA/account-consolidation#7]
While I have not reviewed what these modules do, when searching for information on consolidation at v9, I discovered this repo.  After I did some R&D, what my most of my customers need by consolidation is already supported by Odoo:

[https://www.odoo.com/forum/help-1/question/consolidation-accounts-in-odoo-9-100109]

**Comment by pedrobaeza** [comment]
There are advanced consolidation options that requires distribution percentages or similar that can fit in this repo, so for now I won't remove it.

**Comment by bistaray** [comment]
OK.  Although I have not tried, I understand how to redefine Financial report lines via the GUI to combine (roll up, distribute, etc) compatible (but not identical) charts and calculate percentages when working with balances.  I don't know of any 'advanced' consolidation option that isn't supported by the framework as it already exists now.  I was just suggesting a review of what is already provided, which isn't just what I shared in my forum post.  Just trying to save work.  I'm personally interested in the 'advanced' options that I don't know of that would not be supported by the existing framework.

**Comment by pedrobaeza** [comment]
But you're talking about Enterprise reports, so here it also fits other modules for community edition I think. Anyway, I'm not now working with any consolidation need or with enterprise, so I can't say more about both.

**Comment by bistaray** [comment]
Correct.  I am referring to Enterprise reports.  This repository would then be needed for Community edition.  I agree with all of your feedback.

**Comment by sbidoul** [comment]
@bistaray @pedrobaeza should this kind of consolidation work be required in the community version, it should be a fairly natural extension to the existing mis_builder v9.
